# Generated by Django 4.2.27 on 2026-02-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_ops', '0003_systemprompt_llmmodel_system_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmmodel',
            name='model_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
