# Generated by Django 4.2.27 on 2026-02-13 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_ops', '0006_populate_default_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llmmodel',
            name='documentation_url',
        ),
    ]
